enhancement/apply_pom_style
losete/spring-boot-hexagonal-architecture pull request #19
Opened 2019-10-21 11:59 UTC by losete

Pull Request made for applying the [Maven Code Style And Code Conventions](https://maven.apache.org/developers/conventions/code.html) on pom.xml files

2019-10-22 08:18 UTC, pablogalegoc requested changes

2019-10-22 08:18 UTC, PabloGalegoC commented on pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.
Following the [generic maven code style and conventions](https://maven.apache.org/developers/conventions/code.html)
Line wrapping: Always use a 120-column line width.
Same issue in the other pom.xml

2019-10-22 08:18 UTC, PabloGalegoC commented on domain/pom.xml
>              <scope>test</scope>
Over indented lines

2019-10-22 08:18 UTC, PabloGalegoC commented on application/pom.xml
>  <?xml version="1.0" encoding="UTF-8"?>
Over indented file

2019-10-22 10:54 UTC, pablogalegoc submitted a review, later dismissed

2019-10-22 11:22 UTC, franrua commented
`Applied requested changes` is not a good commit message, because is related with the PR. If I see the git log isolated, can't know what changes was asked for.

2019-10-22 11:25 UTC, franrua requested changes
Each pom section must has their header. You can see your partners pom files.

2019-10-24 06:06 UTC, franrua requested changes
Apply headers and delimiters using reference pom as guide

2019-10-24 06:06 UTC, franrua commented on bootloader/pom.xml
> +
Part of the header is missing.  There are ending delimiters. Review reference pom.

```  
<!-- ///////////////// -->

  <!-- Build Settings -->
```

2019-10-24 06:06 UTC, franrua commented on application/pom.xml
> +  <!-- Dependencies -->
This section doesn't appear in the reference pom. Dependencies are included in Pom relationship section.

2019-10-24 08:09 UTC, franrua submitted a review, later dismissed

2019-10-24 08:28 UTC, pablogalegoc submitted a review, later dismissed

2019-10-24 09:04 UTC, pablogalegoc approved these changes

2019-10-24 09:11 UTC, merged